server:
  port: 8084

spring:
  application:
    name: stats-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/motus_stats
    username: ${DB_USER:motus}
    password: ${DB_PASSWORD:motus}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
